func toggleSwitches() {
    moveForward()
    jump()
    moveForward()
    toggleSwitch()
    turnLeft()
    moveForward()
    toggleSwitch()
    turnLeft()
    turnLeft()
    move(distance: 2)
    toggleSwitch()
    turnRight()
    moveForward()
    jump()
    moveForward()
    turnRight()
    moveForward()
    turnRight()
}

let newStair = Stair()
world.place(newStair, facing: .south, atColumn: 3, row: 3)

moveForward()
jump()
move(distance: 3)
toggleSwitches()
turnRight()
toggleSwitches()
turnRight()
turnRight()
toggleSwitches()
