let expert = Expert()

world.place(expert, facing: .south, atColumn: 1, row: 5)
expert.turnLock(up: false, numberOfTimes: 1)
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.collectGem()
expert.moveForward()
expert.collectGem()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.move(distance: 3)
expert.turnLeft()
expert.move(distance: 3)
expert.collectGem()
expert.move(distance: 1)
expert.collectGem()
expert.turnLock(up: true, numberOfTimes: 1)
expert.turnRight()
expert.moveForward()
expert.collectGem()
expert.move(distance: 2)
expert.collectGem()
expert.moveForward()
expert.collectGem()
