let character = Character()
let expert = Expert()

world.place(character, facing: .north, atColumn: 0, row: 0)
world.place(expert, facing: .north, atColumn: 3, row: 0)

character.collectGem()
character.jump()
character.jump()
character.collectGem()
character.jump()
character.jump()
character.collectGem()
character.turnRight()
character.jump()
character.jump()
character.collectGem()
character.jump()
character.jump()
character.collectGem()
character.turnLeft()

expert.turnLock(up: true, numberOfTimes: 1)
expert.toggleSwitch()

character.move(distance: 2)
character.collectGem()
