// 枠１

Expert()

// 枠２

Character()

// 枠３

expert.turnLock(up: true, numberOfTimes: 4)
expert.turnLeft()
expert.turnLock(up: true, numberOfTimes: 4)
expert.turnLeft()
expert.turnLock(up: true, numberOfTimes: 4)
expert.turnLeft()
expert.turnLock(up: true, numberOfTimes: 4)

character.move(distance: 2)
character.collectGem()
character.turnRight()
character.move(distance: 2)
character.collectGem()
character.turnRight()
character.move(distance: 4)
character.collectGem()
character.turnRight()
character.move(distance: 1)

expert.turnLock(up: false, numberOfTimes: 3)
expert.turnLeft()
expert.turnLock(up: false, numberOfTimes: 3)
expert.turnLeft()
expert.turnLock(up: false, numberOfTimes: 3)
expert.turnLeft()
expert.turnLock(up: false, numberOfTimes: 3)

character.turnLeft()
character.move(distance: 1)
character.collectGem()
character.turnLeft()
character.turnLeft()
character.move(distance: 2)
character.turnRight()
character.move(distance: 2)
character.collectGem()
character.turnLeft()
character.turnLeft()
character.move(distance: 2)
character.turnRight()
character.move(distance: 2)
character.turnRight()
character.move(distance: 2)
character.collectGem()
character.turnLeft()
character.turnLeft()
character.move(distance: 2)
character.turnRight()
character.move(distance: 2)
character.collectGem()
