// 枠１

Expert()

// 枠２

expert.moveForward()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.collectGem()
expert.turnLockDown()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.collectGem()
